p3 fix in hostfilman
File
"/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/hosts/hostfilman.py",
line 247, in getLinksForVideo
    playerUrl = base64.b64decode(self.cm.ph.getSearchGroups(item,
'''data-iframe=['"]([^"^']+?)['"]''')[0]).replace('\\', '')
TypeError: a bytes-like object is required, not 'str'