p2p3 > fix type issue and int arythmetic in urlparserhelper
TypeError: string indices must be integers
// pushes PY3 to use int arythmetic, because int() gives wrong results
for big numbers E.g. int(250263628386554294 / 1)